"""initial warehouse schema

Revision ID: 50005851d8fd
Revises: 
Create Date: 2026-07-08 00:44:57.416589

"""
from alembic import op
import sqlalchemy as sa


revision = '50005851d8fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts_cache',
    sa.Column('contact_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('species', sa.Text(), nullable=True),
    sa.Column('channel', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_table('rfm_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('contact_id', sa.Text(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('recency_days', sa.Integer(), nullable=True),
    sa.Column('order_count', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=0), nullable=True),
    sa.Column('touch_count', sa.Integer(), nullable=True),
    sa.Column('r_score', sa.SmallInteger(), nullable=True),
    sa.Column('f_score', sa.SmallInteger(), nullable=True),
    sa.Column('m_score', sa.SmallInteger(), nullable=True),
    sa.Column('e_score', sa.SmallInteger(), nullable=True),
    sa.Column('segment', sa.Text(), nullable=True),
    sa.Column('persona_guess', sa.Text(), nullable=True),
    sa.Column('persona_confidence', sa.Text(), nullable=True),
    sa.Column('lead_pillar', sa.Text(), nullable=True),
    sa.Column('journey_stage', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', 'run_date', name='uq_rfm_snapshots_contact_run')
    )
    op.create_index('idx_rfm_snapshots_contact', 'rfm_snapshots', ['contact_id', 'run_date'], unique=False)
    op.create_index('idx_rfm_snapshots_run_date', 'rfm_snapshots', ['run_date'], unique=False)
    op.create_index('idx_rfm_snapshots_segment', 'rfm_snapshots', ['run_date', 'segment'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('trigger', sa.Text(), nullable=False),
    sa.Column('contacts_count', sa.Integer(), nullable=True),
    sa.Column('orders_count', sa.Integer(), nullable=True),
    sa.Column('calls_count', sa.Integer(), nullable=True),
    sa.Column('sms_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('language_pref', sa.Text(), nullable=False),
    sa.Column('numerals_pref', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('sync_runs')
    op.drop_index('idx_rfm_snapshots_segment', table_name='rfm_snapshots')
    op.drop_index('idx_rfm_snapshots_run_date', table_name='rfm_snapshots')
    op.drop_index('idx_rfm_snapshots_contact', table_name='rfm_snapshots')
    op.drop_table('rfm_snapshots')
    op.drop_table('contacts_cache')
    # ### end Alembic commands ###
